### ISSUE TITLE
How to catch exceptions in Websocket thread?

### ISSUE THREAD

**Issue by mejmo** [nlsdfnbch/bitex#113]
I am gathering data from Bitfinex so it is important for me to have stable connection. However Bitfinex is having problems in peaks and during these moments Bitfinex connector stops always working.  

One of exceptions is following:

```
2017-12-06 02:51:18,677 handle_data: 200 not registered - Payload: [200, 'te', [110088616, 1512525076070, '-1.157', '0.038084']]
Exception in thread Processing Thread:
Traceback (most recent call last):
  File "C:\DEV\Python36-32\lib\site-packages\bitex\api\WSS\bitfinex.py", line 545, in handle_data
    self.channels[chan_id](ts, chan_id, data)
KeyError: 200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DEV\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\DEV\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\DEV\Python36-32\lib\site-packages\bitex\api\WSS\bitfinex.py", line 343, in process
    self.handle_data(ts, data)
  File "C:\DEV\Python36-32\lib\site-packages\bitex\api\WSS\bitfinex.py", line 548, in handle_data
    "Payload: %s" % (chan_id, msg))
bitex.api.WSS.exceptions.NotRegisteredError: handle_data: 200 not registered - Payload: [200, 'te', [110088616, 1512525076070, '-1.157', '0.038084']]
```
Second exception occured during `_handle_pong`, unfortunately I did not save it

How can I catch these exception so that I could restart the connection? Is there any parameter? For instance I will do a workaround (if I do not receive any data for couple of seconds, I will restart it), but it would be nice to resolve it somehow cleaner.

**Comment by nlsdfnbch** [comment]
Hey @mejmo ,
thanks for submitting this!
It's important to know that the websocket clients in `BitEx` are no longer maintained and are deprecated.

If you're looking for a Bitfinex Client, check out [BtfxWss](https://github.com/nlsdfnbch/btfxwss) though - this should handle dropped reconnects and the key error shouldn't happen either.

I actively maintain the code base there, so I can help you out with any issues on there. 

Cheers,
Nils
