### ISSUE TITLE
Pair Formatter not working anymore?

### ISSUE THREAD

**Issue by bebosudo** [nlsdfnbch/bitex#139]
On the latest dev branch:
```
$ git checkout dev
$ python
>>> from bitex import BTCUSD, Kraken
>>> btcusd = BTCUSD()
>>> resp = Kraken().ticker(btcusd)
~/Documents/projects/bitex/bitex/api/base.py:54: IncompleteCredentialsWarning: Incomplete Credentials were given - authentication may not work!
  IncompleteCredentialsWarning)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    resp = Kraken().ticker(btcusd)
  File "~/Documents/projects/bitex/bitex/utils.py", line 60, in wrapped
    raise AssertionError("%s is not supported by this exchange!" % pair)
AssertionError: BTCUSD is not supported by this exchange!
>>> btcusd
'BTCUSD'
>>> type(btcusd)
<class 'str'>
```

**Comment by bebosudo** [comment]
Figured out now:
```
>>> from bitex import Bitfinex, BTCUSD, Kraken
>>> resp = Bitfinex().ticker(BTCUSD)
>>> resp.json()
{'mid': '14736.0', 'bid': '14735.0', 'ask': '14737.0', 'last_price': '14736.0', 'low': '12200.0', 'high': '14961.0', 'volume': '80567.41819109', 'timestamp': 
'1514047484.9134007'}
>>> resp2 = Kraken().ticker(BTCUSD)
>>> resp2.json()
{'error': [], 'result': {'XXBTZUSD': {'a': ['15262.00000', '1', '1.000'], 'b': ['15216.50000', '1', '1.000'], 'c': ['15215.00000', '0.02910000'], 'v': ['2694.
36289949', '4818.29321154'], 'p': ['14636.04025', '14244.06997'], 't': [20824, 31849], 'l': ['13499.90000', '12498.60000'], 'h': ['15600.00000', '15600.00000'
], 'o': '13874.10000'}}}
```

I definitely have to write it down in the docs 😂
