### ISSUE TITLE
BitfinexWSS.ping() broken

### ISSUE THREAD

**Issue by yuriiz** [nlsdfnbch/bitex#142]
Calling BitfinexWSS.ping() results in
```
Initialized API with version 2
Exception in thread Processing Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/u/.local/lib/python3.6/site-packages/bitex/api/WSS/bitfinex.py", line 346, in process
    self.handle_response(ts, data)
  File "/home/u/.local/lib/python3.6/site-packages/bitex/api/WSS/bitfinex.py", line 381, in handle_response
    self._event_handlers[event](ts, **resp)
TypeError: _handle_pong() got multiple values for argument 'ts'
```

Version BitEx==1.2.11 (latest from PyPi)

**Comment by nlsdfnbch** [comment]
The websocket clients are deprecated and are no longer maintained - if you want to access Bitfinex's WSS API, have a look at [`Btfxwss`](https://github.com/nlsdfnbch/btfxwss)
