### ISSUE TITLE
Bitfinex issue?

### ISSUE THREAD

**Issue by jm789** [nlsdfnbch/bitex#143]
I'm fairly new to this, so I may be missing something obvious.

I've just installed BitEx via pip and confirmed that it's running v1.2.11, I'm trying to connect to Bitfinex with the following code:

**********************
```python
#!/usr/bin/env python
from bitex import Bitfinex

c = Bitfinex(key="xxx",  secret="xxx")

print(c.balance())

*******************

Running the code, generates the following error:

*******************
No handlers could be found for logger "bitex"
Traceback (most recent call last):
  File "mt_bitfinex_getbalances_v1_0.py", line 2, in <module>
    from bitex import Bitfinex
  File "/usr/local/lib/python2.7/site-packages/bitex/__init__.py", line 5, in <module>
    from bitex.interfaces import Kraken, Bitfinex, Bitstamp, CCEX, Coincheck
  File "/usr/local/lib/python2.7/site-packages/bitex/interfaces/__init__.py", line 1, in <module>
    from bitex.interfaces.bitfinex import Bitfinex
  File "/usr/local/lib/python2.7/site-packages/bitex/interfaces/bitfinex.py", line 11, in <module>
    from bitex.api.REST import BitfinexREST
  File "/usr/local/lib/python2.7/site-packages/bitex/api/__init__.py", line 1, in <module>
    import bitex.api.REST
  File "/usr/local/lib/python2.7/site-packages/bitex/api/REST/__init__.py", line 1, in <module>
    from bitex.api.REST.bitfinex import BitfinexREST
  File "/usr/local/lib/python2.7/site-packages/bitex/api/REST/bitfinex.py", line 13, in <module>
    from bitex.api.REST.api import APIClient
  File "/usr/local/lib/python2.7/site-packages/bitex/api/REST/api.py", line 18
    class APIClient(metaclass=ABCMeta):
```
*********************
Am I missing any prerequisites or modules?

**Comment by Casey7747** [comment]
I'm also new to this :)
I believe the current dev branch has the latest version, are you using it or the master?  It seems to be working for me and has been updated regularly. 
Also i am running python3. 

Hope this helps.

**Comment by nlsdfnbch** [comment]
`bitex` only supports python 3.5+. That's why you're missing the `abc` module.
