### ISSUE TITLE
SyntaxError: can use starred expression only as assignment target

### ISSUE THREAD

**Issue by DickVicious** [nlsdfnbch/bitex#98]
### Overview Description
I get an error when trying to import the Bitfinex API interface

# Steps to Reproduce

1. Clone repo
2. Navigate to tests directory
3. run `python api.py`

# Actual Results
```
Traceback (most recent call last):
  File "api.py", line 9, in <module>
    from bitex.api.REST.api import APIClient
  File "/home/user/Documents/Hedge-Fund/Python/lib/python3.4/site-packages/bitex/__init__.py", line 1, in <module>
    from bitex.interfaces import Kraken, Bitfinex, Bitstamp, CCEX, Coincheck
  File "/home/user/Documents/Hedge-Fund/Python/lib/python3.4/site-packages/bitex/interfaces/__init__.py", line 1, in <module>
    from bitex.interfaces.bitfinex import Bitfinex
  File "/home/user/Documents/Hedge-Fund/Python/lib/python3.4/site-packages/bitex/interfaces/bitfinex.py", line 11, in <module>
    from bitex.api.REST.rest import BitfinexREST
  File "/home/user/Documents/Hedge-Fund/Python/lib/python3.4/site-packages/bitex/api/__init__.py", line 2, in <module>
    import bitex.api.WSS
  File "/home/user/Documents/Hedge-Fund/Python/lib/python3.4/site-packages/bitex/api/WSS/__init__.py", line 1, in <module>
    from bitex.api.WSS.bitfinex import BitfinexWSS
  File "/home/user/Documents/Hedge-Fund/Python/lib/python3.4/site-packages/bitex/api/WSS/bitfinex.py", line 570
    entry = (*data, ts)
                    ^
SyntaxError: can use starred expression only as assignment target`
```

# Expected Results
For the script to run, or at least get past the import function

# Reproducibility
Happens every time for me

# Additional Information:
I tried with `pip install bitex` as well as cloning the repo and running the test api.py file

**Comment by nlsdfnbch** [comment]
Hey @DickVicious,
`bitex` only supports python versions `3.5+`.
the unpacking you see there is a feature introduced in 3.5. You're wlcome to submit a PR that replaces this, but support for earlier Python versions is not on my road map. 

Sorry!

Nils
